import localFont from "next/font/local";
import type { Metadata } from "next";
import "./globals.css";

// Geist Sans
const geistSans = localFont({
  src: [
    { path: "./public/fonts/GeistSans-Regular.woff2", weight: "400", style: "normal" },
    { path: "./public/fonts/GeistSans-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-geist-sans",
});

// Geist Mono
const geistMono = localFont({
  src: [
    { path: "./public/fonts/GeistMono-Regular.woff2", weight: "400", style: "normal" },
    { path: "./public/fonts/GeistMono-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Uni Track",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
